[package]
name = "anabolix-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tide = "0.16.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tide-governor = "1.0.3"
http-types = "2.12.0"
